[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ServerRoot,
    [int]$MaxRequests = 0
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'RustRPG-Common.ps1')
. (Join-Path $PSScriptRoot 'RustRPG-Operations.ps1')
. (Join-Path $PSScriptRoot 'RustRPG-Services.ps1')

$Config=Get-RustRemoteAccessConfig -ServerRoot $ServerRoot
if(-not[bool]$Config.enabled){throw "L'acces distant est desactive."}
$AccessToken=Get-RustRemoteAccessToken -ServerRoot $ServerRoot
if(-not$AccessToken){throw "Le jeton distant est absent ou illisible pour cet utilisateur Windows."}
$BindIp=if([string]$Config.bindAddress-eq'0.0.0.0'){[Net.IPAddress]::Any}else{[Net.IPAddress]::Loopback}
$Listener=[Net.Sockets.TcpListener]::new($BindIp,[int]$Config.port)
$FailedLogins=@{}
$RequestCount=0
$LogPath=Join-Path $ServerRoot 'logs\remote-dashboard.log'
[IO.Directory]::CreateDirectory((Split-Path $LogPath -Parent))|Out-Null

function Write-RemoteLog([string]$Message){Add-Content -LiteralPath $LogPath -Encoding UTF8 -Value ((Get-Date -Format 'yyyy-MM-dd HH:mm:ss')+' - '+$Message)}
function ConvertTo-RemoteJson($Value){return ($Value|ConvertTo-Json -Depth 12 -Compress)}
function Test-TokenEqual([string]$Left,[string]$Right){
    if($null-eq$Left-or$null-eq$Right){return $false};$A=[Text.Encoding]::UTF8.GetBytes($Left);$B=[Text.Encoding]::UTF8.GetBytes($Right);$Diff=$A.Length-bxor$B.Length;$Length=[math]::Max($A.Length,$B.Length);for($i=0;$i-lt$Length;$i++){$Av=if($i-lt$A.Length){$A[$i]}else{0};$Bv=if($i-lt$B.Length){$B[$i]}else{0};$Diff=$Diff-bor($Av-bxor$Bv)};return $Diff-eq 0
}
function Write-HttpResponse($Stream,[int]$Status,[string]$ContentType,[string]$Body,[hashtable]$ExtraHeaders=@{}){
    $Reason=switch($Status){200{'OK'}202{'Accepted'}400{'Bad Request'}401{'Unauthorized'}403{'Forbidden'}404{'Not Found'}409{'Conflict'}429{'Too Many Requests'}500{'Internal Server Error'}default{'OK'}}
    $Bytes=[Text.Encoding]::UTF8.GetBytes($Body);$Headers=[ordered]@{'Content-Type'=$ContentType+'; charset=utf-8';'Content-Length'=[string]$Bytes.Length;'Connection'='close';'Cache-Control'='no-store';'X-Content-Type-Options'='nosniff';'X-Frame-Options'='DENY';'Referrer-Policy'='no-referrer';'Content-Security-Policy'="default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:"}
    foreach($Key in $ExtraHeaders.Keys){$Headers[$Key]=$ExtraHeaders[$Key]};$HeaderText="HTTP/1.1 $Status $Reason`r`n"+(($Headers.GetEnumerator()|ForEach-Object{$_.Key+': '+$_.Value})-join"`r`n")+"`r`n`r`n";$HeaderBytes=[Text.Encoding]::ASCII.GetBytes($HeaderText);$Stream.Write($HeaderBytes,0,$HeaderBytes.Length);$Stream.Write($Bytes,0,$Bytes.Length);$Stream.Flush()
}
function Get-RemoteHtml {
return @'
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rust Server Control Center</title><style>
:root{color-scheme:dark;--bg:#0e0d0b;--panel:#171614;--line:#302c27;--text:#f0e8de;--muted:#9b9288;--rust:#d65332;--ok:#72d79b;--amber:#e7a84d}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Bahnschrift,"Arial Narrow",sans-serif}header{height:64px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 24px;gap:14px;background:#11100e}header b{font-size:20px;letter-spacing:.04em}main{max-width:1180px;margin:0 auto;padding:28px 20px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:18px 0}input,button{border:1px solid #49433d;background:#171614;color:var(--text);padding:10px 13px;font:700 13px inherit;border-radius:3px}input{font-weight:400;min-width:280px}button{cursor:pointer}button.primary{background:var(--rust);border-color:var(--rust)}button:hover{filter:brightness(1.15)}.status{margin-left:auto;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px}.server{border:1px solid var(--line);background:var(--panel);padding:18px;border-radius:3px}.server h2{font-size:19px;margin:0 0 4px}.meta{color:var(--muted);font-size:12px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.metric{border-top:1px solid #39332d;padding-top:9px}.metric strong{display:block;font-size:18px}.metric span{font-size:10px;color:var(--muted)}.state{font-size:11px;font-weight:800;color:var(--rust)}.state.on{color:var(--ok)}.actions{display:flex;gap:7px;flex-wrap:wrap}.danger{border-color:#713d32}.notice{border-left:3px solid var(--amber);background:#201a13;padding:12px;color:#d8c5aa}.hidden{display:none}#login{max-width:480px;margin:80px auto;border:1px solid var(--line);padding:24px;background:var(--panel)}#message{color:var(--amber);min-height:20px}@media(max-width:620px){header{padding:0 14px}header b{font-size:16px}.status{display:none}main{padding:18px 12px}.metrics{grid-template-columns:repeat(2,1fr)}input{min-width:100%;width:100%}}
</style></head><body><header><b>RUST SERVER CONTROL CENTER</b><span class="status" id="connection">LOCAL SECURISE</span></header><main><section id="login"><h1>Connexion</h1><p class="meta">Saisis le jeton généré dans l’application Windows. Il reste seulement dans cet onglet.</p><div class="toolbar"><input id="token" type="password" autocomplete="current-password" placeholder="Jeton d’accès"><button class="primary" onclick="login()">OUVRIR</button></div><div id="loginError" class="state"></div></section><section id="app" class="hidden"><h1>Mes serveurs</h1><div class="notice">L’accès Internet direct est déconseillé. Pour l’extérieur, utilise un VPN ou un proxy HTTPS ; n’ouvre jamais le port RCON.</div><div class="toolbar"><button onclick="refresh()">ACTUALISER</button><span id="message"></span></div><div id="servers" class="grid"></div></section></main><script>
let token=sessionStorage.getItem('rustControlToken')||'';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json','X-Rust-Control':'1'},body:body?JSON.stringify(body):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}async function login(){token=document.getElementById('token').value.trim();try{await api('/api/status');sessionStorage.setItem('rustControlToken',token);showApp();refresh()}catch(e){document.getElementById('loginError').textContent=e.message}}function showApp(){document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden')}async function refresh(){try{const d=await api('/api/status');document.getElementById('connection').textContent='ACTUALISE '+new Date().toLocaleTimeString();document.getElementById('servers').innerHTML=d.instances.map(s=>`<article class="server"><span class="state ${s.Running?'on':''}">${s.Running?'ACTIF':'ARRETE'}</span><h2>${esc(s.DisplayName)}</h2><div class="meta">${esc(s.Identity)} · ${esc(s.Isolation)}</div><div class="metrics"><div class="metric"><strong>${s.MemoryMb}</strong><span>MEMOIRE Mo</span></div><div class="metric"><strong>${s.Players}</strong><span>JOUEURS</span></div><div class="metric"><strong>${s.Fps}</strong><span>FPS</span></div></div><div class="actions"><button class="primary" onclick="act('${encodeURIComponent(s.InstanceId)}','start')">DEMARRER</button><button class="danger" onclick="act('${encodeURIComponent(s.InstanceId)}','stop')">ARRETER</button><button onclick="act('${encodeURIComponent(s.InstanceId)}','restart')">REDEMARRER</button><button onclick="act('${encodeURIComponent(s.InstanceId)}','backup')">SAUVEGARDER</button></div></article>`).join('')}catch(e){msg(e.message)}}async function act(id,action){try{const d=await api('/api/instances/'+id+'/'+action,'POST',{});msg(d.message||'Action demandée');setTimeout(refresh,1200)}catch(e){msg(e.message)}}function msg(t){document.getElementById('message').textContent=t}if(token){showApp();refresh()}
</script></body></html>
'@
}
function Get-RequestBody($Reader,[int]$Length){if($Length-le0){return ''};if($Length-gt32768){throw 'Corps de requete trop volumineux.'};$Buffer=New-Object char[] $Length;$Read=0;while($Read-lt$Length){$N=$Reader.Read($Buffer,$Read,$Length-$Read);if($N-le0){break};$Read+=$N};return -join $Buffer[0..([math]::Max(0,$Read-1))]}

$Listener.Start();Write-RemoteLog "Ecoute sur $($Config.bindAddress):$($Config.port)."
try{
# La limite sert aux tests d'integration et doit aussi fonctionner pour les
# routes qui terminent leur traitement par `continue`.
while($MaxRequests-le0-or$RequestCount-lt$MaxRequests){
    $Client=$Listener.AcceptTcpClient();$RequestCount++
    try{
        $Client.ReceiveTimeout=10000;$Client.SendTimeout=10000;$Stream=$Client.GetStream();$Reader=New-Object IO.StreamReader($Stream,[Text.Encoding]::UTF8,$false,4096,$true);$RequestLine=$Reader.ReadLine();if(-not$RequestLine){continue};$Parts=$RequestLine.Split(' ');if($Parts.Count-lt2){throw 'Requete HTTP invalide.'};$Method=$Parts[0].ToUpperInvariant();$RawPath=$Parts[1];$Headers=@{};while($true){$Line=$Reader.ReadLine();if([string]::IsNullOrEmpty($Line)){break};$Sep=$Line.IndexOf(':');if($Sep-gt0){$Headers[$Line.Substring(0,$Sep).Trim().ToLowerInvariant()]=$Line.Substring($Sep+1).Trim()}}
        $Remote=[string]$Client.Client.RemoteEndPoint;$Ip=$Remote.Split(':')[0];$Length=if($Headers.ContainsKey('content-length')){[int]$Headers['content-length']}else{0};$Body=Get-RequestBody $Reader $Length;$Path=($RawPath.Split('?')[0]);
        if($Path-eq'/health'){Write-HttpResponse $Stream 200 'application/json' (ConvertTo-RemoteJson @{status='ok';version='12.1.0'});continue}
        if($Path-eq'/'-and$Method-eq'GET'){Write-HttpResponse $Stream 200 'text/html' (Get-RemoteHtml);continue}
        $Now=Get-Date;$Failures=if($FailedLogins.ContainsKey($Ip)){@($FailedLogins[$Ip]|Where-Object{($Now-$_).TotalMinutes-lt10})}else{@()};$Auth=if($Headers.ContainsKey('authorization')){[string]$Headers['authorization']}else{''};$Given=if($Auth.StartsWith('Bearer ')){$Auth.Substring(7)}else{''}
        if($Failures.Count-ge5){Write-HttpResponse $Stream 429 'application/json' (ConvertTo-RemoteJson @{error='Trop de tentatives. Reessaie dans dix minutes.'});continue}
        if(-not(Test-TokenEqual $Given $AccessToken)){$FailedLogins[$Ip]=@($Failures)+@($Now);Write-RemoteLog "Authentification refusee depuis $Remote";Write-HttpResponse $Stream 401 'application/json' (ConvertTo-RemoteJson @{error='Jeton invalide.'}) @{'WWW-Authenticate'='Bearer'};continue}
        if($Method-ne'GET'-and(-not$Headers.ContainsKey('x-rust-control'))){Write-HttpResponse $Stream 403 'application/json' (ConvertTo-RemoteJson @{error='En-tete de controle absent.'});continue}
        if($Path-eq'/api/status'-and$Method-eq'GET'){$Instances=@(Get-RustServerInstances -ServerRoot $ServerRoot|ForEach-Object{Get-RustInstanceTelemetry -ServerRoot $ServerRoot -Instance $_});Write-HttpResponse $Stream 200 'application/json' (ConvertTo-RemoteJson @{generatedUtc=[datetime]::UtcNow.ToString('o');instances=$Instances});continue}
        if($Path-match'^/api/instances/([a-z0-9-]+)/(start|stop|restart|backup)$'-and$Method-eq'POST'){
            $Id=[Uri]::UnescapeDataString($Matches[1]);$Action=$Matches[2];$Instance=Get-RustServerInstance -ServerRoot $ServerRoot -Id $Id;if(-not$Instance){Write-HttpResponse $Stream 404 'application/json' (ConvertTo-RemoteJson @{error='Instance introuvable.'});continue};$Running=@(Get-RustRpgServerProcesses -ServerRoot $ServerRoot|Where-Object Identity -eq([string]$Instance.identity))|Select-Object -First 1
            if($Action-eq'start') {if($Running){throw 'Instance deja active.'};$null=Set-RustDesiredState -ServerRoot $ServerRoot -InstanceId $Id -State Running -Reason remote;$PsExe=Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe';$null=Start-Process -FilePath $PsExe -ArgumentList @('-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',('"'+(Join-Path $ServerRoot 'Start-Instance.ps1')+'"'),'-InstanceId',$Id) -WorkingDirectory $ServerRoot -WindowStyle Hidden;Write-RemoteLog "Demarrage distant $Id"}
            elseif($Action-eq'stop'){if(-not$Running){throw 'Instance deja arretee.'};$null=Set-RustDesiredState -ServerRoot $ServerRoot -InstanceId $Id -State Stopped -Reason remote;try{$null=Invoke-RustRpgRconCommand -ServerRoot $ServerRoot -RconPort ([int]$Instance.rconPort) -Command 'server.save' -TimeoutMs 8000}catch{};$null=Send-RustRpgRconCommand -ServerRoot $ServerRoot -RconPort ([int]$Instance.rconPort) -Command 'quit';Write-RemoteLog "Arret distant $Id"}
            elseif($Action-eq'restart'){if(-not$Running){throw 'Instance arretee : utilise Demarrer.'};$null=Set-RustDesiredState -ServerRoot $ServerRoot -InstanceId $Id -State Stopped -Reason remote;try{$null=Invoke-RustRpgRconCommand -ServerRoot $ServerRoot -RconPort ([int]$Instance.rconPort) -Command 'server.save' -TimeoutMs 8000}catch{};$null=Send-RustRpgRconCommand -ServerRoot $ServerRoot -RconPort ([int]$Instance.rconPort) -Command 'quit';$Deadline=(Get-Date).AddSeconds(30);do{Start-Sleep -Milliseconds 500;$RunningNow=@(Get-RustRpgServerProcesses -ServerRoot $ServerRoot|Where-Object Identity -eq([string]$Instance.identity)).Count}while($RunningNow-and(Get-Date)-lt$Deadline);if($RunningNow){throw "Le serveur ne s'est pas arrete dans le delai."};$null=Set-RustDesiredState -ServerRoot $ServerRoot -InstanceId $Id -State Running -Reason remote;$PsExe=Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe';$null=Start-Process -FilePath $PsExe -ArgumentList @('-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',('"'+(Join-Path $ServerRoot 'Start-Instance.ps1')+'"'),'-InstanceId',$Id) -WorkingDirectory $ServerRoot -WindowStyle Hidden;Write-RemoteLog "Redemarrage distant $Id"}
            else{if($Running){$null=Invoke-RustRpgRconCommand -ServerRoot $ServerRoot -RconPort ([int]$Instance.rconPort) -Command 'server.save' -TimeoutMs 8000;Start-Sleep -Seconds 2};$Backup=New-RustServerBackup -ServerRoot $ServerRoot -Identity ([string]$Instance.identity) -Kind 'remote' -AllowRunning:$([bool]$Running);Write-RemoteLog "Sauvegarde distante $Id : $Backup"}
            Write-HttpResponse $Stream 202 'application/json' (ConvertTo-RemoteJson @{ok=$true;message="Action $Action acceptee pour $($Instance.displayName)."});continue
        }
        if($Path-eq'/api/rcon'-and$Method-eq'POST'){if(-not[bool]$Config.allowRcon){Write-HttpResponse $Stream 403 'application/json' (ConvertTo-RemoteJson @{error='Console RCON distante desactivee.'});continue};$Data=$Body|ConvertFrom-Json;$Id=[string]$Data.instanceId;$Command=[string]$Data.command;if(-not$Command-or$Command.Length-gt256-or$Command-match'[\r\n]'){throw 'Commande RCON invalide.'};$Instance=Get-RustServerInstance -ServerRoot $ServerRoot -Id $Id;if(-not$Instance){throw 'Instance introuvable.'};$Response=Invoke-RustRpgRconCommand -ServerRoot $ServerRoot -RconPort ([int]$Instance.rconPort) -Command $Command;Write-RemoteLog "Commande RCON distante $Id : $Command";Write-HttpResponse $Stream 200 'application/json' (ConvertTo-RemoteJson @{response=$Response});continue}
        Write-HttpResponse $Stream 404 'application/json' (ConvertTo-RemoteJson @{error='Route introuvable.'})
    }catch{try{Write-RemoteLog ('Erreur requete : '+$_.Exception.Message);Write-HttpResponse $Stream 500 'application/json' (ConvertTo-RemoteJson @{error=$_.Exception.Message})}catch{}}
    finally{if($Reader){$Reader.Dispose()};if($Stream){$Stream.Dispose()};$Client.Close()}
}}
finally{$Listener.Stop();Write-RemoteLog 'Service arrete.'}
